---
- name: "Setting up JupyterLab Elyra globally"
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
      ignore_errors: true 

    - name: Dependencies
      apt:
        name: -f
        state: present

    - name: Install python3-pip, nodejsand npm
      apt:
        name:
          - python3-pip
          - nodejs
          - npm
        state: present
      ignore_errors: true  

    - name: Upgrade pip to latest
      ansible.builtin.pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install JupyterLab
      ansible.builtin.pip:
        name: jupyterlab==3.2.1
        executable: pip3

    - name: Install Elyra globally
      ansible.builtin.pip:
        name: elyra==3.15.0
        executable: pip3

    - name: Restart JupyterHub service
      systemd:
        name: jupyterhub
        state: restarted
      ignore_errors: true
