---
- name: "Deploying System with Elyra"
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Fix broken dependencies and upgrade packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Upgrade pip to the latest version
      ansible.builtin.pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install Elyra globally without dependency conflicts
      ansible.builtin.pip:
        name: elyra
        executable: pip3
        extra_args: "--ignore-installed"

    - name: Verify Elyra installation
      command: pip3 show elyra
      register: elyra_installation
      failed_when: "'elyra' not in elyra_installation.stdout"
      changed_when: false

    - name: Confirm Elyra version
      command: jupyter labextension list
      register: labextensions
      changed_when: false
